### ISSUE TITLE
Issues with ?stringTest=dynamic

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/sound-waves#37]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/974, with ?stringTest=dynamic I am seeing two issues:
1. The units on the ruler:
<img width="336" alt="Screenshot 2023-08-30 at 3 57 10 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/dc3eca67-6e7d-4a5e-add7-07cc292051f9">

2. The scales for Wall Position and Wall Angle can become misaligned:
<img width="283" alt="Screenshot 2023-08-30 at 4 01 04 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/0f62ec15-37b4-426e-af72-d65d453315fd">
<img width="283" alt="Screenshot 2023-08-30 at 4 01 14 PM" src="https://github.com/phetsims/sound-waves/assets/87318828/89b2a656-b017-4e1e-a1ab-9a450bd171f5">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Sound Waves‬
URL: https://phet-dev.colorado.edu/html/sound-waves/1.0.0-rc.2/phet/sound-waves_all_phet.html?stringTest=dynamic
Version: 1.0.0-rc.2 2023-08-28 14:05:18 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
Language: en-US
Window: 1269x729
Pixel Ratio: 2/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by KatieWoe** [comment]
I also saw some oddities if strings were long next to checkboxes.
![checkboxsmall](https://github.com/phetsims/sound-waves/assets/41024075/07d6b322-bdd7-47d5-8181-be3a95e6fc7d)

**Comment by matthew-blackman** [comment]
The issue with ruler is documented in https://github.com/phetsims/scenery-phet/issues/817. Although it is outside the scope of the Sound Waves publication, we should address the dynamic layout issues with RulerNode long-term.

Will address the panel layout issues and leave the ruler alone for this RC.

**Comment by matthew-blackman** [comment]
This is ready for QA spot-check on main. All dynamic layout issues described above should be fixed except for the ruler for the reasons above.

**Comment by KatieWoe** [comment]
I'm still seeing the oddly sized text with long strings on the last screen. With dynamic strings and without.
<img width="203" alt="stillsmall" src="https://github.com/phetsims/sound-waves/assets/41024075/4fbc4b7e-ff88-44db-9c56-25b7e9d86ce6">

**Comment by matthew-blackman** [comment]
The sound mode radio button text was also scaling incorrectly with long strings. Fixed in above commit. We also shortened the "Air Density in Speaker Box" string which was causing the text in the panels on the last screen to shrink more than on other screens.

@marlitas and I are still a bit confused as to how the text across panels is maintaining a single font size, but I think it looks okay and we are happy with the current way that text is dynamically laying out. Ready for spot-check!

**Comment by KatieWoe** [comment]
Looks much better on main now

**Comment by Nancy-Salpepi** [comment]
Everything looks good to me too!

**Comment by Nancy-Salpepi** [comment]
Looks good to me in rc.2. Closing
